%%-*- mode: erlang -*-
case os:getenv("CUTTLEFISH_ESCRIPT") =:= "true" of
    true ->
        PostHooks = {post_hooks, [ {"(linux|darwin|solaris|win32)", app_compile, "make escript"}
                                 , {"(freebsd|netbsd|openbsd)", app_compile, "gmake escript"}]},
        [PostHooks | CONFIG];
    false ->
        %% building escript, delete the post hook
        lists:keydelete(post_hooks, 1, CONFIG)
end.
